name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: cd
        run: cd front

      - name: Install
        run: npm install --prefix ./front

      - name: Build
        run: npm run build --prefix ./front

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 
        with:
          publish_dir: ./front/dist 
          github_token: ${{ secrets.FRONT_DEPLOY }}
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: Todo List